[
    {
        "heading": "How an AI-based technology can make quick offside decisions at the FIFA World Cup",
        "subHeading": "The semi-automated VAR, an artificial-intelligence-based technology, is likely to be deployed at the World Cup later this year.",
        "description": "One of the biggest criticisms of the Video Assistant Referee (VAR) in football is it takes too long, thus impacting the flow of the match. In some cases, as per FIFA, the VAR has taken up to four minutes to take offside decisions. Now, a technology has been proposed that promises to reduce that time to just three or four seconds.The semi-automated VAR, an artificial-intelligence-based technology, is likely to be deployed at the World Cup later this year, the International Football Association Board (IFAB), the organisation that forms the rules of the game, has indicated.“It looks very good and very promising,” FIFA president Gianni Infantino said on Monday. “Our experts are looking into [the trials] before we take a decision on whether it will be used for the World Cup or not.",
        "img": "https://images.indianexpress.com/2022/06/VAR.jpg",
        "imgSrc": "The semi-automated method is to make quick offside decisions. (File)",
        "author": "Sayak Dutta",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "India vs South Africa (IND vs SA) 3rd T20 Match Live Streaming: When and where to watch?",
        "subHeading": "India vs SA Live Streaming Details: India and South Africa will clash with each other in Vizag for 3rd T20",
        "description": "Live Streaming of India Vs South Africa,3rd T20 Match: Tuesday will present India with the final chance to keep the five-T20I series against South Africa alive as the two teams take the field in Vizag. Having already lost in Delhi and Cuttack, the Rishabh Pant led side have a big task at hand to win the next three games in the absence of some big regulars in the squad. India were on the receiving end of a record T20I chase at the Arun Jaitley Stadium in the first T20I as David Miller and Rassie van der Dussen took the visitors past the finish line in Delhi. On Sunday, defending a low total on a tricky wicket, India got off to a good start courtesy of a Bhuvneshwar Kumar new ball special but lost the track against a player of the match outing by Heinrich Klassen. The Proteas are unbeaten against India in seven games this year across formats, having won two Tests, two T20Is and three ODIs.",
        "img": "https://images.indianexpress.com/2022/06/Unheadingd-design-38.jpg",
        "imgSrc": "IND vs SA LIVE Streaming: When and How to watch; Check Out Here",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Possible FIFA ban, future of coach Stimac and over-reliance on Chhetri: As India qualify for Asian Cup, focus shifts on other pressing issues",
        "subHeading": "The road to the Asian Cup though, was made needlessly hard by an Indian team that underperformed against teams ranked below them.",
        "description": "The Indian national football team qualified for the 2023 AFC Asian Cup as one of the eleven teams that could have gone through in the third round of the qualifiers. Their qualification was confirmed when the Philippines lost 0-4 to Palestine in a Group B encounter on Tuesday. The result means that this is the first time in AFC Asian Cup history that India has managed to qualify on back-to-back tournaments. It will only be the fifth time that the national team will be appearing in Asia’s biggest continental competition. The back-to-back participation is a sign of consistency that is crucial required for Indian football to grow. Rather than currently unobtainable goals like qualification for the World Cup or the Olympics, consistently getting better at the Asian level is what is needed for the national team. And to get better in Asia requires qualifying for its premier competition on a regular basis.",
        "img": "https://images.indianexpress.com/2022/06/Unheadingd-design-3-2.jpg",
        "imgSrc": "Sunil Chhetri looked to have secured India a second straight win after they beat Cambodia on Wednesday with an 86th-minute free kick, only for Zubayr Amiri's header two minutes later to pull the Afghans level. (Twitter/IndianFootballTeam)",
        "author": "Shashank Nair",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Sri Lanka vs Australia (SL vs AUS) 1st ODI Live Streaming: When and where to watch match live?",
        "subHeading": "Sri Lanka vs Australia (SL vs AUS) 1st ODI Live Streaming: Sri Lanka are hosting Australia for a five-match ODI series starting on Tuesday.",
        "description": "Sri Lanka vs Australia (SL vs AUS) 1st ODI Live Streaming: Sri Lanka and Australia are all set to lock horns in the first ODI of the five-match 50-overs series on Tuesday. In the latest injury setback to the touring side, fast bowler Kane Richardson has been ruled out of the series. Richardson will be flying home and has been replaced by fast bowler Scott Boland for the series. Australia, who won the three-match T20 series 2-1, will also play two tests in Sri Lanka.",
        "img": "https://images.indianexpress.com/2022/06/Untitled-design-31.jpg",
        "imgSrc": "SL vs AUS 1st ODI: Australian skipper Aaron Finch with Sri Lankan captain Dasun Shanaka.",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Indonesia Open: PV Sindhu, Sai Praneeth bow out",
        "subHeading": "Seventh seed PV Sindhu lost 14-21, 18-21 to Bing Jiao in the women's singles.",
        "description": "P V Sindhu made a shock first round exit from the Indonesia Open Super 1000 event after suffering a straight-game defeat against China’s He Bing Jiao, here on Tuesday. Seventh seed Sindhu lost 14-21, 18-21 to Bing Jiao in the women’s singles. Sindhu, a former world champion, has won two Super 300 titles — the Syed Modi International and the Swiss Open — this season. By virtue of this win, world No. 9 Bing Jiao, whom Sindhu had defeated at the Badminton Asia Championship, lead the Indian 10-8 on head-to-head record. The defeat at the Istora Gelora Bung Karno has affected Sindhu’s preparations for the next month’s Commonwealth Games in Birmingham. Also bowing out was B Sai Praneeth, who lost 16-21 19-21 to Hans-Kristian Solberg Vittinghus of Denmark in the men’s singles. The mixed doubles pair of Ishaan Bhatnagar and Tanisha Crasto faced similar fate, crashing out in the opening round after losing 14-21 11-21 to Hong Kong combination of Chang Tak Ching and NG Wing Yung Hong in just 32 minutes.",
        "img": "https://images.indianexpress.com/2022/04/PV-SIndhu.jpg",
        "imgSrc": "P V Sindhu faltered in the Indonesia Open. (BAI)",
        "author": "PTI",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Andrew Redmayne: The dancing goalie who took Australia to the 2022 World Cup",
        "subHeading": "From having almost quit football, to taking his country to the World Cup, the 33-year old goalkeeper has had quite the journey.",
        "description": "The 33-year old goalkeeper was the only one apart from the Australia head coach, Graham Arnold, who had secretly informed Redmayne that he’d be making an appearance towards the end of the game. And he did. Replacing captain Matt Ryan, Australia’s goalkeeper for majority of the 90 minutes and extra time, the Sydney FC goalkeeper stood tall at the end of the penalty shootout to ensure his country featured at the FIFA World Cup finals for the fifth consecutive time. “Maty was full of support coming off and then just before penalties as well, he was pumping me up and getting me ready…when we were in a huddle he said ‘you’ve got this mate, this is all you’,” Redmayne said after the match. Graham Arnold later confirmed that the Australia captain wasn’t aware of the change happening until his number went up on the fourth official board, stating that he understood why this was happening just ahead of the penalty shootout. Redmayne’s reputation as a penalty shootout super sub goalkeeper hadn’t grown overnight. On his way, he took a road of self-discovery, having almost quit the game that gave him last night and a place in Australian folklore.",
        "img": "https://images.indianexpress.com/2022/06/Australia-FIFA-World-Cup.jpg",
        "imgSrc": "Australia players celebrate with Andrew Redmayne (in grey) after beating Peru in the penalty shootout on Monday night. (Courtesy: Socceroos/Twitter)",
        "author": "Rahul Pandey",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Watch: Are you kidding me? Fan surprises Roger Federer with a tattoo he got in his honor",
        "subHeading": "Federer, who has undergone a third surgery on his knee, is eyeing a return to action at the Laver Cup in London at the end of September.",
        "description": "Roger Federer’s recovery from knee surgery is going slowly and his world ranking has slumped to 50, his lowest in 22 years. But the twenty-time Grand Slam champion still have an incredible fan following. Roger Federer has plenty of super fans around the world and one of them saw his dreams turned into reality by the Swiss superstar. In a video posted on Instagram, a fan can be heard saying he got a tattoo in Federer’s honor, while also calling the former World No. 1 his ‘biggest inspiration.’ After looking at the tattoo, the 40-year-old said, ‘Are you kidding me?’ before hugging the fan.",
        "img": "https://images.indianexpress.com/2022/06/Roger-Federer.jpeg",
        "imgSrc": "Roger Federer meets his super fan in a restaurant. (Screengrab)",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "NBA Finals: Golden State Warriors beat Boston Celtics 104-94, go 3-2 up",
        "subHeading": "The Warriors are now one win away from their fourth title in eight years.",
        "description": "The Golden State Warriors beat the Boston Celtics 104-94 on Monday to take a 3-2 lead in the best-of-seven NBA Finals series. Andrew Wiggins and Klay Thompson did most of the damage for the Warriors, combining for 47 points, while the visitors committed 18 turnovers and had 10 missed free throws in the contest. After poor shooting saw them trail by 12 points at halftime, the Celtics opened the third quarter on a 10-0 run and took their first lead of the night at 58-55 on a three-pointer from Al Horford. But Jordan Poole’s bank shot from half court at the third quarter buzzer sent the momentum firmly in Golden State’s direction, and the home team put the game out of reach with an emphatic Wiggins dunk in the fourth.",
        "img": "https://images.indianexpress.com/2022/06/Stephen-Curry-2.jpg",
        "imgSrc": "Golden State Warriors guard Stephen Curry (30) celebrates after a three-point basket during the second half in game five of the 2022 NBA Finals against the Boston Celtics at Chase Center. (USA TODAY Sports)",
        "author": "Reuters",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Megan Rapinoe, Alex Morgan back for US for World Cup qualifiers",
        "subHeading": "The United States is the two-time defending World Cup champion.",
        "description": "Megan Rapinoe and Alex Morgan have been included on the US roster for next month’s CONCACAF W Championship, which will determine four of the region’s teams in the 2023 Women’s World Cup. Rapinoe and Morgan have not been on a US roster since last October as coach Vlatko Andonovski evaluated younger players in the run-up to qualifying. The United States is the two-time defending World Cup champion. “So excited to be back with my gals!” Alex Morgan tweeted following Monday’s announcement. Twenty-three players were named to the qualifying roster, and three others — Sam Coffey, Carson Pickett and Jaelin Howell — were added to the training camp in advance of a pair of friendlies later this month against Colombia. Several players were left off the squad because of injuries, including Sam Mewis (knee), Abby Dahlkemper (ribs) and Lynn Williams (hip). Catarina Macario tore her ACL recently while playing with her club team, Lyon, and is out for at least six months.",
        "img": "https://images.indianexpress.com/2022/06/Megan-Rapinoe-Alex-Morgan.jpg",
        "imgSrc": "Megan Rapinoe (right) and Alex Morgan have been included in the US soccer team. (AP)",
        "author": "AP",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Harry Kane discusses Qatar stance with Christian Eriksen, Hugo Lloris",
        "subHeading": "Kane, who said in March that the England squad had met to discuss the issues ahead of the tournament, said he had been talking with players from other countries, including former Tottenham Hotspur team mate Eriksen and current Spurs goalkeeper Hugo Lloris.",
        "description": "England captain Harry Kane said he has spoken to France skipper Hugo Lloris and Denmark’s Christian Eriksen about their national teams taking a unified stance on human rights issues surrounding this year’s World Cup in Qatar. Homosexuality is illegal in Qatar while a report by Amnesty International found that thousands of migrant workers in the country were being exploited. The Qatar government, which has denied the accusations in the Amnesty report, said it had introduced various reforms in the last five years, including a new national minimum wage and the removal of exit permits. Kane, who said in March that the England squad had met to discuss the issues ahead of the tournament, said he had been talking with players from other countries, including former Tottenham Hotspur team mate Eriksen and current Spurs goalkeeper Hugo Lloris. “Christian Eriksen got in touch with me a couple of weeks ago now,” Kane told reporters on Monday. “Obviously there is Hugo Lloris, who I am in touch with a lot anyway. So the discussion was there to maybe do something as a collective.",
        "img": "https://images.indianexpress.com/2022/06/Harry-Kane.jpg",
        "imgSrc": "England's Harry Kane reacts during their match against Italy. (Twitter/UEFA Nations League)",
        "author": "Reuters",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "While You Were Asleep: Australia qualify for Qatar 2022, Croatia shock winless France, Ronaldo pens down heartfelt note to Marcelo",
        "subHeading": "More than a teammate, a brother that football gave me, wrote Cristiano Ronaldo in an emotional note to former Real Madrid teammate Marcelo; Australia have reached their fifth consecutive World Cup.",
        "description": "Australia have qualified for the 2022 World Cup following a 5-4 penalty shootout win over Peru in their intercontinental playoff on Monday. Australia have reached their fifth consecutive World Cup.  Substitute goalkeeper Redmayne was the hero for Australia with two key penalty saves. Luis Advincula and Alex Valera miss spot-kicks for Peru.Australia will meet defending champion France in the opening game of Group D on November 22, and take on Tunisia and Denmark. The final place at the World Cup will be filled in the same stadium on Tuesday when Costa Rica meets New Zealand. This was Croatia’s first win over France comes at the tenth attempt. In the previous nine encounters, they have lost six and drawn three. The red-hot Croats have lost only one of their last 13 games, and have only failed to score in one of their last 12 Nations League fixtures. They have kept five clean sheets in their last six away internationals.Meanwhile, the World Cup holders France have only kept one clean sheet in their last nine UEFA Nations League matches. Cristiano Ronaldo and Marcelo had an incredible nine years playing down the left-wing together for Real Madrid. They had a telepathic relationship. Brazilian full-back Marcelo on Monday bids adieu to Real Madrid, and his former teammate Cristiano Ronaldo paid tribute with an emotional note on social media.",
        "img": "https://images.indianexpress.com/2022/06/While-You-Were-Asleep-7.jpg",
        "imgSrc": "Cristiano Ronaldo (left) played nine years with Marcelo at Real Madrid; Australian players celebrate after winning in a penalty shoot-out during the World Cup 2022 qualifying play-off soccer match between Australia and Peru in Al Rayyan, Qatar. (Twitter/Cristiano Ronaldo & AP)",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Khelo India: Haryana girls shine as boxers help state lift the championship trophy, prize money doubled",
        "subHeading": "At the end of the day, the biggest cheer was reserved for the boxers when Union minister of sports Anurag Thakur handed over the trophy to boxers and other players at the Fourth Khelo India Youth Games at the Indradhanush Auditorium in Sector 5.",
        "description": "Haryana boxers hogged the limelight on the last day of the Khelo India Youth Games here on Monday, with a few more girls becoming the state’s pride and joy by bagging gold medals in different boxing categories and helping the state lift the overall championship trophy. Neha, daughter of an Army havildar, won gold in the girls’ 54kg final with a win over Aarti Dhariya of Uttarakhand. “My father always wanted me to be a boxer. When I shifted from Jhajjar to Hisar to train under coach M S Dhaka at the SAI centre, I had to stay away from my family. But whenever I won a medal, my father would tell his friends and relatives about my achievement. To win the gold medal and to help Haryana become the overall champions is a special moment for all of us,” said Neha. Preeti of Silana village near Sonepat also did Haryana proud by winning a gold medal in the girls’ 60 kg category with a win over Kappana of Rajasthan. With her maternal uncle Deepak Hooda being the Indian kabaddi captain, Preeti had initially taken up kabaddi before switching to boxing. She too shifted to Hisar to train under coach M S Dhaka. She has won more than nine international medals, including a gold each in the 2019 Asian Junior Boxing Championship in Dubai and 2021 Asian Youth Boxing Championship in Dubai.",
        "img": "https://images.indianexpress.com/2022/06/Haryana-Boxing.jpg",
        "imgSrc": "Haryana girls boxing team after winning the overall championship in girls category in Khelo India Games. (Express Photo by Nitin Sharma)",
        "author": "Nitin Sharma",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Ahead of Worlds, Javelin champ Neeraj Chopra hopes to work towards Tokyo magic in much-awaited return",
        "subHeading": "Neeraj Chopra isn’t obsessed with the 90m mark, after all his famous gold was won at 87.58 metres.",
        "description": "For javelin throwers participating at the Paavo Nurmi Games in Turku, Finland, there’s always an added incentive. Breaking the Finnish national record at the spiritual home of javelin throw entitles one to a major bonus. Four years ago, throwers who went past 93.09 metres were promised the title deed to an island. This wasn’t a prank. This year’s incentive will appeal to Olympic gold medallist Neeraj Chopra. The owner of a second-hand Ford Mustang – he had rewarded himself with the American muscle car for making history in Tokyo – has been alerted about the eco-friendly electric option. A day before Chopra makes his much-anticipated return after the Olympics, organisers smartly tweeted: “Mr. First-Ever Indian Olympic Champion is in the house! Neeraj Chopra (@Neeraj_chopra1), it’s a pleasure to have you in #Turku! Javelin will be EPIC!! Also, how would a Ford Mustang Match-E sound like? Over 93.09m aaand (sic) have a nice ride.” A picture of a relaxed-looking Chopra, with a baseball cap worn backwards and standing in front of a large poster with a black and white cut-out of the legendary distance runner, popularly known as flying Finn and owner of nine Olympic gold medals, was part of the social media post. Ten months after the Tokyo high, Chopra will compete for the first time on Tuesday night in Turku. Temperatures are a cool 18 degree Celsius and a light drizzle is predicted soon after the javelin competition. Turku will feel welcoming till the throwers reach the call room.",
        "img": "https://images.indianexpress.com/2022/05/Neeraj-Chopra-gold.jpg",
        "imgSrc": "Staying injury-free will be the immediate area of focus for Neeraj Chopra.(File)",
        "author": "Nihal Koshie",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Bigger coffers through IPL, higher pension to ex-players",
        "subHeading": "IPL media rights: Unprecedented bidding for media rights runs parallel to sharp hike in cricketers’ and umpires’ pension",
        "description": "On a day when the IPL media rights bidding war guaranteed nearly Rs 45,000 crore (and counting) to the BCCI coffers over the next five years, the cricket board turned to the country’s former cricketers and umpires, giving their monthly pensions a substantial hike. With effect from June 1, existing monthly pensions of Rs 15,000, Rs 22,500, Rs 30,000, Rs 37,500 and Rs 50,000 have been revised to Rs 30,000, Rs 45,000, Rs 52,500, Rs 60,000 and Rs 70,000. The BCCI confirmed this via a press release, as its president Sourav Ganguly said: “The players remain the lifeline and as a Board, it is our duty to be by their side once their playing days are over.” Secretary Jay Shah added: “The welfare of our cricketers, be it former and present, is a top priority, and increasing pension amounts is a step in that direction.” The BCCI’s gesture was welcomed by former Indian women’s team captain Diana Edulji. “I thank the BCCI for this wonderful gift of increasing pensions across the board. It will help a number of players in their twilight zone,” she told The Indian Express. “It’s a great gesture by the Indian board. This will really help players, especially those who have played in the ‘60s and ‘70s,” said ex-India captain Dilip Vengsarkar. Moving on to the IPL media rights auction, the highlight so far has been an exponential growth in the digital rights value. On Day 2 of the e-auction, Package B that dealt with the digital rights in the Indian subcontinent, was taken at Rs 50 crore per game, securing a 51.5 per cent jump over its base price of Rs 33 crore per match, even after Amazon’s pull-out. Package A, TV rights for the Indian subcontinent, was parked at Rs 57.5 crore per game, a 17.3 per cent hike over its base price of Rs 49 crore. It is likely that for the first time, the IPL will have different broadcasters for TV and digital streaming in India.",
        "img": "https://images.indianexpress.com/2022/05/GT-trophy.jpg",
        "imgSrc": "The IPL’s valuation, according to Duff & Phelps, was $5.9 billion two years ago. (Sportzpics for IPL)",
        "author": "Shamik Chakrabarty",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "What India need to do to qualify for Asian Cup and where to watch",
        "subHeading": "India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers",
        "description": "Sunil Chhetri-led India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers at the Salt Lake Stadium in Kolkata on Tuesday. In the first match, Sunil Chhetri, returning from injury, pumped two goals past Cambodia for a 2-0 win and the start they needed. Then came Afghanistan. For 86 minutes, nothing could separate both teams. Then Chhetri did what he does – curling in a freekick from right outside the box into Afghanistan’s net. Two minutes later, India conceded from a corner. But then in extra time, Sahal Abdul Samad came up with a winner to help India make it two wins in two games. A win or a draw now brings the surety of making back-to-back Asian Cups – something that has not been done by the Indian team ever. This is what India need to do to qualify for the continental championship: Results to look out for will be the Philippines vs Palestine match. The Philippines are currently second in their group with 4 points. A loss or a draw would mean that India cannot be the worst of six second-placed teams. Also below India are Malaysia and Indonesia. If they draw or lose the final game of their group, then the same scenario happens wherein India isn’t the worst of the second-placed teams left and therefore qualify for the 2023 AFC Asian Cup. ",
        "img": "https://images.indianexpress.com/2022/06/Sunil-Chhetri-.jpg?resize=450,250",
        "imgSrc": "Sunil Chhetri-led India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers. (Twitter/Indian football team)",
        "author": "Express News Service",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Aishwarya breaks decade-old triple jump record with 14.14m",
        "subHeading": "The semi-automated VAR, an artificial-intelligence-based technology, is likely to be deployed at the World Cup later this year.",
        "description": "One of the biggest criticisms of the Video Assistant Referee (VAR) in football is it takes too long, thus impacting the flow of the match. In some cases, as per FIFA, the VAR has taken up to four minutes to take offside decisions. Now, a technology has been proposed that promises to reduce that time to just three or four seconds.The semi-automated VAR, an artificial-intelligence-based technology, is likely to be deployed at the World Cup later this year, the International Football Association Board (IFAB), the organisation that forms the rules of the game, has indicated.“It looks very good and very promising,” FIFA president Gianni Infantino said on Monday. “Our experts are looking into [the trials] before we take a decision on whether it will be used for the World Cup or not.",
        "img": "https://images.indianexpress.com/2022/06/Aishwarya-long-jump-india.jpg?resize=450,250",
        "imgSrc": "The semi-automated method is to make quick offside decisions. (File)",
        "author": "Sayak Dutta",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "BCCI doubles pension of former umpires, players",
        "subHeading": "India vs SA Live Streaming Details: India and South Africa will clash with each other in Vizag for 3rd T20",
        "description": "Live Streaming of India Vs South Africa,3rd T20 Match: Tuesday will present India with the final chance to keep the five-T20I series against South Africa alive as the two teams take the field in Vizag. Having already lost in Delhi and Cuttack, the Rishabh Pant led side have a big task at hand to win the next three games in the absence of some big regulars in the squad. India were on the receiving end of a record T20I chase at the Arun Jaitley Stadium in the first T20I as David Miller and Rassie van der Dussen took the visitors past the finish line in Delhi. On Sunday, defending a low total on a tricky wicket, India got off to a good start courtesy of a Bhuvneshwar Kumar new ball special but lost the track against a player of the match outing by Heinrich Klassen. The Proteas are unbeaten against India in seven games this year across formats, having won two Tests, two T20Is and three ODIs.",
        "img": "https://images.indianexpress.com/2020/03/bcci-logo-fb.jpg?resize=450,250",
        "imgSrc": "IND vs SA LIVE Streaming: When and How to watch; Check Out Here",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Haryana is ultimate Khelo India champion",
        "subHeading": "The road to the Asian Cup though, was made needlessly hard by an Indian team that underperformed against teams ranked below them.",
        "description": "The Indian national football team qualified for the 2023 AFC Asian Cup as one of the eleven teams that could have gone through in the third round of the qualifiers. Their qualification was confirmed when the Philippines lost 0-4 to Palestine in a Group B encounter on Tuesday. The result means that this is the first time in AFC Asian Cup history that India has managed to qualify on back-to-back tournaments. It will only be the fifth time that the national team will be appearing in Asia’s biggest continental competition. The back-to-back participation is a sign of consistency that is crucial required for Indian football to grow. Rather than currently unobtainable goals like qualification for the World Cup or the Olympics, consistently getting better at the Asian level is what is needed for the national team. And to get better in Asia requires qualifying for its premier competition on a regular basis.",
        "img": "https://images.indianexpress.com/2022/06/khelo-india-2022.jpg?resize=450,250",
        "imgSrc": "Sunil Chhetri looked to have secured India a second straight win after they beat Cambodia on Wednesday with an 86th-minute free kick, only for Zubayr Amiri's header two minutes later to pull the Afghans level. (Twitter/IndianFootballTeam)",
        "author": "Shashank Nair",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "For the first time since 2003, Roger Federer, Novak Djokovic & Rafael Nadal missing from top 2 of rankings",
        "subHeading": "Sri Lanka vs Australia (SL vs AUS) 1st ODI Live Streaming: Sri Lanka are hosting Australia for a five-match ODI series starting on Tuesday.",
        "description": "Sri Lanka vs Australia (SL vs AUS) 1st ODI Live Streaming: Sri Lanka and Australia are all set to lock horns in the first ODI of the five-match 50-overs series on Tuesday. In the latest injury setback to the touring side, fast bowler Kane Richardson has been ruled out of the series. Richardson will be flying home and has been replaced by fast bowler Scott Boland for the series. Australia, who won the three-match T20 series 2-1, will also play two tests in Sri Lanka.",
        "img": "https://images.indianexpress.com/2020/02/djokovic-nadal-federer-1200.jpg?resize=450,250",
        "imgSrc": "SL vs AUS 1st ODI: Australian skipper Aaron Finch with Sri Lankan captain Dasun Shanaka.",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Sneha, Ritu put Himachal on the women’s boxing map",
        "subHeading": "Seventh seed PV Sindhu lost 14-21, 18-21 to Bing Jiao in the women's singles.",
        "description": "P V Sindhu made a shock first round exit from the Indonesia Open Super 1000 event after suffering a straight-game defeat against China’s He Bing Jiao, here on Tuesday. Seventh seed Sindhu lost 14-21, 18-21 to Bing Jiao in the women’s singles. Sindhu, a former world champion, has won two Super 300 titles — the Syed Modi International and the Swiss Open — this season. By virtue of this win, world No. 9 Bing Jiao, whom Sindhu had defeated at the Badminton Asia Championship, lead the Indian 10-8 on head-to-head record. The defeat at the Istora Gelora Bung Karno has affected Sindhu’s preparations for the next month’s Commonwealth Games in Birmingham. Also bowing out was B Sai Praneeth, who lost 16-21 19-21 to Hans-Kristian Solberg Vittinghus of Denmark in the men’s singles. The mixed doubles pair of Ishaan Bhatnagar and Tanisha Crasto faced similar fate, crashing out in the opening round after losing 14-21 11-21 to Hong Kong combination of Chang Tak Ching and NG Wing Yung Hong in just 32 minutes.",
        "img": "https://images.indianexpress.com/2022/06/boxing-ritu-sneha-kumari.jpg?resize=450,250",
        "imgSrc": "P V Sindhu faltered in the Indonesia Open. (BAI)",
        "author": "PTI",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "‘You deserve to be here. Just keep doing what you have done in the past’: Kohli to RCB pacer Akash Deep",
        "subHeading": "From having almost quit football, to taking his country to the World Cup, the 33-year old goalkeeper has had quite the journey.",
        "description": "The 33-year old goalkeeper was the only one apart from the Australia head coach, Graham Arnold, who had secretly informed Redmayne that he’d be making an appearance towards the end of the game. And he did. Replacing captain Matt Ryan, Australia’s goalkeeper for majority of the 90 minutes and extra time, the Sydney FC goalkeeper stood tall at the end of the penalty shootout to ensure his country featured at the FIFA World Cup finals for the fifth consecutive time. “Maty was full of support coming off and then just before penalties as well, he was pumping me up and getting me ready…when we were in a huddle he said ‘you’ve got this mate, this is all you’,” Redmayne said after the match. Graham Arnold later confirmed that the Australia captain wasn’t aware of the change happening until his number went up on the fourth official board, stating that he understood why this was happening just ahead of the penalty shootout. Redmayne’s reputation as a penalty shootout super sub goalkeeper hadn’t grown overnight. On his way, he took a road of self-discovery, having almost quit the game that gave him last night and a place in Australian folklore.",
        "img": "https://images.indianexpress.com/2022/06/virat-kohli-akashdeep.jpg?resize=450,250",
        "imgSrc": "Australia players celebrate with Andrew Redmayne (in grey) after beating Peru in the penalty shootout on Monday night. (Courtesy: Socceroos/Twitter)",
        "author": "Rahul Pandey",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Requires courage when you are treated unfairly: Mithali Raj on feud with Ramesh Powar",
        "subHeading": "Federer, who has undergone a third surgery on his knee, is eyeing a return to action at the Laver Cup in London at the end of September.",
        "description": "Roger Federer’s recovery from knee surgery is going slowly and his world ranking has slumped to 50, his lowest in 22 years. But the twenty-time Grand Slam champion still have an incredible fan following. Roger Federer has plenty of super fans around the world and one of them saw his dreams turned into reality by the Swiss superstar. In a video posted on Instagram, a fan can be heard saying he got a tattoo in Federer’s honor, while also calling the former World No. 1 his ‘biggest inspiration.’ After looking at the tattoo, the 40-year-old said, ‘Are you kidding me?’ before hugging the fan.",
        "img": "https://images.indianexpress.com/2022/06/mithali-raj-ramesh-powar.jpg?resize=450,250",
        "imgSrc": "Roger Federer meets his super fan in a restaurant. (Screengrab)",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Marcelo bids adieu: Real Madrid legends break down in emotional farewell",
        "subHeading": "The Warriors are now one win away from their fourth title in eight years.",
        "description": "The Golden State Warriors beat the Boston Celtics 104-94 on Monday to take a 3-2 lead in the best-of-seven NBA Finals series. Andrew Wiggins and Klay Thompson did most of the damage for the Warriors, combining for 47 points, while the visitors committed 18 turnovers and had 10 missed free throws in the contest. After poor shooting saw them trail by 12 points at halftime, the Celtics opened the third quarter on a 10-0 run and took their first lead of the night at 58-55 on a three-pointer from Al Horford. But Jordan Poole’s bank shot from half court at the third quarter buzzer sent the momentum firmly in Golden State’s direction, and the home team put the game out of reach with an emphatic Wiggins dunk in the fourth.",
        "img": "https://images.indianexpress.com/2022/06/marcelo-farewell.jpg?resize=450,250",
        "imgSrc": "Golden State Warriors guard Stephen Curry (30) celebrates after a three-point basket during the second half in game five of the 2022 NBA Finals against the Boston Celtics at Chase Center. (USA TODAY Sports)",
        "author": "Reuters",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "With Asian Cup berth on the line, India take on Hong Kong",
        "subHeading": "The United States is the two-time defending World Cup champion.",
        "description": "Megan Rapinoe and Alex Morgan have been included on the US roster for next month’s CONCACAF W Championship, which will determine four of the region’s teams in the 2023 Women’s World Cup. Rapinoe and Morgan have not been on a US roster since last October as coach Vlatko Andonovski evaluated younger players in the run-up to qualifying. The United States is the two-time defending World Cup champion. “So excited to be back with my gals!” Alex Morgan tweeted following Monday’s announcement. Twenty-three players were named to the qualifying roster, and three others — Sam Coffey, Carson Pickett and Jaelin Howell — were added to the training camp in advance of a pair of friendlies later this month against Colombia. Several players were left off the squad because of injuries, including Sam Mewis (knee), Abby Dahlkemper (ribs) and Lynn Williams (hip). Catarina Macario tore her ACL recently while playing with her club team, Lyon, and is out for at least six months.",
        "img": "https://images.indianexpress.com/2022/06/india-football-team.jpg?resize=450,250",
        "imgSrc": "Megan Rapinoe (right) and Alex Morgan have been included in the US soccer team. (AP)",
        "author": "AP",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Ranji Trophy SF: Mumbai have slight upper hand against Uttar Pradesh",
        "subHeading": "Kane, who said in March that the England squad had met to discuss the issues ahead of the tournament, said he had been talking with players from other countries, including former Tottenham Hotspur team mate Eriksen and current Spurs goalkeeper Hugo Lloris.",
        "description": "England captain Harry Kane said he has spoken to France skipper Hugo Lloris and Denmark’s Christian Eriksen about their national teams taking a unified stance on human rights issues surrounding this year’s World Cup in Qatar. Homosexuality is illegal in Qatar while a report by Amnesty International found that thousands of migrant workers in the country were being exploited. The Qatar government, which has denied the accusations in the Amnesty report, said it had introduced various reforms in the last five years, including a new national minimum wage and the removal of exit permits. Kane, who said in March that the England squad had met to discuss the issues ahead of the tournament, said he had been talking with players from other countries, including former Tottenham Hotspur team mate Eriksen and current Spurs goalkeeper Hugo Lloris. “Christian Eriksen got in touch with me a couple of weeks ago now,” Kane told reporters on Monday. “Obviously there is Hugo Lloris, who I am in touch with a lot anyway. So the discussion was there to maybe do something as a collective.",
        "img": "https://images.indianexpress.com/2022/04/ranji-trophy-stock-fb.jpg?resize=450,250",
        "imgSrc": "England's Harry Kane reacts during their match against Italy. (Twitter/UEFA Nations League)",
        "author": "Reuters",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Shuttlers Manashi Joshi, Manisha Ramadass bag gold at Canada Int’l Para Tournament Ottawa",
        "subHeading": "More than a teammate, a brother that football gave me, wrote Cristiano Ronaldo in an emotional note to former Real Madrid teammate Marcelo; Australia have reached their fifth consecutive World Cup.",
        "description": "Australia have qualified for the 2022 World Cup following a 5-4 penalty shootout win over Peru in their intercontinental playoff on Monday. Australia have reached their fifth consecutive World Cup.  Substitute goalkeeper Redmayne was the hero for Australia with two key penalty saves. Luis Advincula and Alex Valera miss spot-kicks for Peru.Australia will meet defending champion France in the opening game of Group D on November 22, and take on Tunisia and Denmark. The final place at the World Cup will be filled in the same stadium on Tuesday when Costa Rica meets New Zealand. This was Croatia’s first win over France comes at the tenth attempt. In the previous nine encounters, they have lost six and drawn three. The red-hot Croats have lost only one of their last 13 games, and have only failed to score in one of their last 12 Nations League fixtures. They have kept five clean sheets in their last six away internationals.Meanwhile, the World Cup holders France have only kept one clean sheet in their last nine UEFA Nations League matches. Cristiano Ronaldo and Marcelo had an incredible nine years playing down the left-wing together for Real Madrid. They had a telepathic relationship. Brazilian full-back Marcelo on Monday bids adieu to Real Madrid, and his former teammate Cristiano Ronaldo paid tribute with an emotional note on social media.",
        "img": "https://images.indianexpress.com/2022/06/para-badminton.jpg?resize=450,250",
        "imgSrc": "Cristiano Ronaldo (left) played nine years with Marcelo at Real Madrid; Australian players celebrate after winning in a penalty shoot-out during the World Cup 2022 qualifying play-off soccer match between Australia and Peru in Al Rayyan, Qatar. (Twitter/Cristiano Ronaldo & AP)",
        "author": "Sports Desk",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Need to train Indian athletes to handle mental pressure at big events: Nikhat Zareen",
        "subHeading": "At the end of the day, the biggest cheer was reserved for the boxers when Union minister of sports Anurag Thakur handed over the trophy to boxers and other players at the Fourth Khelo India Youth Games at the Indradhanush Auditorium in Sector 5.",
        "description": "Haryana boxers hogged the limelight on the last day of the Khelo India Youth Games here on Monday, with a few more girls becoming the state’s pride and joy by bagging gold medals in different boxing categories and helping the state lift the overall championship trophy. Neha, daughter of an Army havildar, won gold in the girls’ 54kg final with a win over Aarti Dhariya of Uttarakhand. “My father always wanted me to be a boxer. When I shifted from Jhajjar to Hisar to train under coach M S Dhaka at the SAI centre, I had to stay away from my family. But whenever I won a medal, my father would tell his friends and relatives about my achievement. To win the gold medal and to help Haryana become the overall champions is a special moment for all of us,” said Neha. Preeti of Silana village near Sonepat also did Haryana proud by winning a gold medal in the girls’ 60 kg category with a win over Kappana of Rajasthan. With her maternal uncle Deepak Hooda being the Indian kabaddi captain, Preeti had initially taken up kabaddi before switching to boxing. She too shifted to Hisar to train under coach M S Dhaka. She has won more than nine international medals, including a gold each in the 2019 Asian Junior Boxing Championship in Dubai and 2021 Asian Youth Boxing Championship in Dubai.",
        "img": "https://images.indianexpress.com/2022/05/Zareen-1200.jpg?resize=450,250",
        "imgSrc": "Haryana girls boxing team after winning the overall championship in girls category in Khelo India Games. (Express Photo by Nitin Sharma)",
        "author": "Nitin Sharma",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Uruguay striker Darwin Núñez set for Liverpool from Benfica",
        "subHeading": "Neeraj Chopra isn’t obsessed with the 90m mark, after all his famous gold was won at 87.58 metres.",
        "description": "For javelin throwers participating at the Paavo Nurmi Games in Turku, Finland, there’s always an added incentive. Breaking the Finnish national record at the spiritual home of javelin throw entitles one to a major bonus. Four years ago, throwers who went past 93.09 metres were promised the title deed to an island. This wasn’t a prank. This year’s incentive will appeal to Olympic gold medallist Neeraj Chopra. The owner of a second-hand Ford Mustang – he had rewarded himself with the American muscle car for making history in Tokyo – has been alerted about the eco-friendly electric option. A day before Chopra makes his much-anticipated return after the Olympics, organisers smartly tweeted: “Mr. First-Ever Indian Olympic Champion is in the house! Neeraj Chopra (@Neeraj_chopra1), it’s a pleasure to have you in #Turku! Javelin will be EPIC!! Also, how would a Ford Mustang Match-E sound like? Over 93.09m aaand (sic) have a nice ride.” A picture of a relaxed-looking Chopra, with a baseball cap worn backwards and standing in front of a large poster with a black and white cut-out of the legendary distance runner, popularly known as flying Finn and owner of nine Olympic gold medals, was part of the social media post. Ten months after the Tokyo high, Chopra will compete for the first time on Tuesday night in Turku. Temperatures are a cool 18 degree Celsius and a light drizzle is predicted soon after the javelin competition. Turku will feel welcoming till the throwers reach the call room.",
        "img": "https://images.indianexpress.com/2022/06/Darwin-Nunez.jpg?resize=450,250",
        "imgSrc": "Staying injury-free will be the immediate area of focus for Neeraj Chopra.(File)",
        "author": "Nihal Koshie",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Kotak, Bali, Bahutule part of India support staff for Ireland tour under Laxman",
        "subHeading": "IPL media rights: Unprecedented bidding for media rights runs parallel to sharp hike in cricketers’ and umpires’ pension",
        "description": "On a day when the IPL media rights bidding war guaranteed nearly Rs 45,000 crore (and counting) to the BCCI coffers over the next five years, the cricket board turned to the country’s former cricketers and umpires, giving their monthly pensions a substantial hike. With effect from June 1, existing monthly pensions of Rs 15,000, Rs 22,500, Rs 30,000, Rs 37,500 and Rs 50,000 have been revised to Rs 30,000, Rs 45,000, Rs 52,500, Rs 60,000 and Rs 70,000. The BCCI confirmed this via a press release, as its president Sourav Ganguly said: “The players remain the lifeline and as a Board, it is our duty to be by their side once their playing days are over.” Secretary Jay Shah added: “The welfare of our cricketers, be it former and present, is a top priority, and increasing pension amounts is a step in that direction.” The BCCI’s gesture was welcomed by former Indian women’s team captain Diana Edulji. “I thank the BCCI for this wonderful gift of increasing pensions across the board. It will help a number of players in their twilight zone,” she told The Indian Express. “It’s a great gesture by the Indian board. This will really help players, especially those who have played in the ‘60s and ‘70s,” said ex-India captain Dilip Vengsarkar. Moving on to the IPL media rights auction, the highlight so far has been an exponential growth in the digital rights value. On Day 2 of the e-auction, Package B that dealt with the digital rights in the Indian subcontinent, was taken at Rs 50 crore per game, securing a 51.5 per cent jump over its base price of Rs 33 crore per match, even after Amazon’s pull-out. Package A, TV rights for the Indian subcontinent, was parked at Rs 57.5 crore per game, a 17.3 per cent hike over its base price of Rs 49 crore. It is likely that for the first time, the IPL will have different broadcasters for TV and digital streaming in India.",
        "img": "https://images.indianexpress.com/2020/12/vvs-laxman-India.jpg?resize=450,250",
        "imgSrc": "The IPL’s valuation, according to Duff & Phelps, was $5.9 billion two years ago. (Sportzpics for IPL)",
        "author": "Shamik Chakrabarty",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
    {
        "heading": "Ranji Trophy 2021-22 semifinals: Schedule, Squads, Venues, Telecast, Live Streaming – All you need to know",
        "subHeading": "India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers",
        "description": "Sunil Chhetri-led India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers at the Salt Lake Stadium in Kolkata on Tuesday. In the first match, Sunil Chhetri, returning from injury, pumped two goals past Cambodia for a 2-0 win and the start they needed. Then came Afghanistan. For 86 minutes, nothing could separate both teams. Then Chhetri did what he does – curling in a freekick from right outside the box into Afghanistan’s net. Two minutes later, India conceded from a corner. But then in extra time, Sahal Abdul Samad came up with a winner to help India make it two wins in two games. A win or a draw now brings the surety of making back-to-back Asian Cups – something that has not been done by the Indian team ever. This is what India need to do to qualify for the continental championship: Results to look out for will be the Philippines vs Palestine match. The Philippines are currently second in their group with 4 points. A loss or a draw would mean that India cannot be the worst of six second-placed teams. Also below India are Malaysia and Indonesia. If they draw or lose the final game of their group, then the same scenario happens wherein India isn’t the worst of the second-placed teams left and therefore qualify for the 2023 AFC Asian Cup. ",
        "img": "https://images.indianexpress.com/2022/06/ranji.jpg?resize=450,250",
        "imgSrc": "Sunil Chhetri-led India will take on Hong Kong in their final match of the AFC Asian Cup qualifiers. (Twitter/Indian football team)",
        "author": "Express News Service",
        "tags": "sports",
        "place": "New Delhi",
        "date": "June 18, 2022 12:06:40 pm",
    },
]